node:
  id: "backend"
  cluster: "microservices-cluster"
admin:
  access_log_path: /tmp/admin_access0.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 4001
static_resources:
  listeners:
  - name: outbound_proxy
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 3001
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress_tcp
          cluster: postgres
          access_log:
            - name: envoy.file_access_log
              config:
                path: "/tmp/outbound-proxy.log"
  clusters:
  - name: spire_agent
    connect_timeout: 0.25s
    http2_protocol_options: {}
    hosts:
      - pipe:
          path: /run/spire/sockets/agent.sock
  - name: postgres
    connect_timeout: 10s
    type: strict_dns
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          address: postgres-envoy
          port_value: 9001
    tls_context:
      common_tls_context:
        tls_certificate_sds_secret_configs:
          - name: "spiffe://yourdomain.com/ns/default/sa/default/backend"
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                  envoy_grpc:
                    cluster_name: spire_agent
        combined_validation_context:
          # validate the SPIFFE ID of the server (recommended)
          default_validation_context:
            match_subject_alt_names:
              exact: "spiffe://yourdomain.com/ns/default/sa/default/postgres"
          validation_context_sds_secret_config:
            name: "spiffe://yourdomain.com"
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                  envoy_grpc:
                    cluster_name: spire_agent
        tls_params:
          ecdh_curves:
            - X25519:P-256:P-521:P-384
