FROM node:lts-alpine as base
WORKDIR /usr/src/app
COPY package*.json ./
EXPOSE 3000

FROM base as dev
ENV NODE_ENV=development
RUN npm install -g nodemon && npm install
COPY . .
CMD ["npm", "run", "start:dev"]