apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
#  labels:
#    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: yourdomain.com.dkr.ecr.eu-central-1.amazonaws.com/webapp-dev:frontend-latest
      imagePullSecrets:
      - name: regcred
